### ISSUE TITLE
Suggestion: When -Export, return path to XML file

### ISSUE THREAD

**Issue by juneb** [janegilring/PSVersionCompare#4]
When you use the Export parameter of Get-PSVersionCommand, the command takes a while to complete and there's no feedback to the user. Because it's not typical for XML files to be written to $home\Documents, it might be helpful to end the command by returning the path to the XML file: 
e.g. return $Path

**Comment by janegilring** [comment]
Great suggestion, per now it`s only returned when specifying -Verbose.

**Comment by janegilring** [comment]
Implemented in https://github.com/janegilring/PSVersionCompare/commit/64027b3f0641f3825f37262de70bb150e8479357

Now you can do for example:
$CommandInfo = Get-PSVersionCommand -Export
Invoke-Item -Path $CommandInfo

**Comment by juneb** [comment]
Nice. Thanks.
