### ISSUE TITLE
Suggestion: Unless differences, don't write to host

### ISSUE THREAD

**Issue by juneb** [janegilring/PSVersionCompare#5]
When there are no differences in the modules, there is no output, but Write-Host still writes:

"Command differences in module <ModuleName>" to the screen, leading users to believe that it found differences.

Either change the message to something like, "Comparing module <ModuleName>" or suppress the message until at least one difference is found in the module.
![screenshot 2016-05-10 20 43 16](https://cloud.githubusercontent.com/assets/2954883/15169467/5d16ff7a-16f0-11e6-9755-784bcf0176a1.png)

**Comment by janegilring** [comment]
That's a good point. Personally I like to see what modules is being compared, so I`ll probably go for the first approach if no one prefers otherwise.

**Comment by janegilring** [comment]
Suggestion implemented in https://github.com/janegilring/PSVersionCompare/commit/3f285eecf8391022f2514a4a122ddd4eb946ee7c

**Comment by juneb** [comment]
Thanks. Good resolution. I think this message is more appropriate for -Verbose than the default, but I'm fine with it.
